Added two new API Methods
Methexis-Inc/SocialAGI pull request #19
Opened 2023-05-02 06:30 UTC by naynaly10

thinkBeforeMessage()
thinkAfterMessage()

togo:
thinkBeforeBegin()
PersonalityObject()

todo:
polish and organize.

2023-05-03 00:48 UTC, kafischer requested changes
AMAZING!!!
🔥🔥🔥

2023-05-03 00:48 UTC, kafischer commented on javascript/src/customization.ts
> +        const strValues = this.values.map(val => val === Complete ? this.fillIn : val).join(' ');
if we're adding a space on the join should probably trim spaces off the ends of each value

2023-05-03 00:48 UTC, kafischer commented on javascript/src/customization.ts
> +    private remembrancePrompt_pt1: string = `Remember you are Samantha, AI Kindred Spirit, and thought provoking conversationalist, as described in the system prompt.` + `Now, think through Samantha'
what's up with the `+` in this string?

2023-05-03 00:48 UTC, kafischer commented on core/examples/example.ts
> +
add eslint and copy the eslint config from https://github.com/Methexis-Inc/SocialAGI/blob/main/server/examples/samantha/.eslintrc.json

requires the following dev dependencies
`
    "eslint": "7.32.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-recommended": "^4.1.0",
    "eslint-plugin-prettier": "^4.2.1",
    "prettier": "^2.7.1",
    `

2023-05-03 00:48 UTC, kafischer commented on core/src/customization.ts
> +export class ThinkingObject {
Let's go with `ThoughtPattern`?

2023-05-03 00:48 UTC, kafischer commented on core/src/customization.ts
> +        const strValues = this.values.map(val => val === Complete ? this.fillIn : val).join(' ');
probably want to trim spaces off ends of the values since we're joining like this

2023-05-03 00:48 UTC, kafischer commented on core/src/customization.ts
> +        return `<${this.type}>${strValues.toLowerCase()}</${this.type}>`;
there should be newlines here after the first tag and before the last one

2023-05-03 00:48 UTC, kafischer commented on core/src/customization.ts
> +    shortContext: string = "is texting someone new at MeetAI.com"
```suggestion
    shortContext: string = "is texting someone new at souls.chat"
```

2023-05-03 00:48 UTC, kafischer commented on core/src/customization.ts
> +    simpleGoal: string = "is to have a super insightful conversation"
```suggestion
    simpleGoal: string = "have a super insightful conversation"
```

2023-05-03 00:48 UTC, kafischer commented on core/src/customization.ts
> +    plan: string = "to ask the user what's on their mind today and use a cool emoji"
```suggestion
    plan: string = "ask the user what's on their mind today and use a cool emoji"
```

2023-05-03 00:48 UTC, kafischer commented on core/src/customization.ts
> +        The plan is ${this.plan}
```suggestion
        The plan is to ${this.plan}
```

2023-05-03 00:48 UTC, kafischer commented on core/src/customization.ts
> +        <BACKGROUND>\n
there's a lot of excess spaces here. need to delete them.

Also the first line needs to not be blank.

2023-05-03 00:48 UTC, kafischer commented on core/src/customization.ts
> +        <BACKGROUND>\n
also remove that newline char

2023-05-03 00:48 UTC, kafischer commented on core/src/customization.ts
> +               `Now, think through ${this.personality.name}'s response to the last message using the following output format.`;
get rid of the + here, make just in the backticks

2023-05-03 00:48 UTC, kafischer commented on core/src/gptTagStream.ts
> +
inconsistent formatting generally - need to add eslint

2023-05-03 00:48 UTC, kafischer commented on core/src/gptTagStream.ts
> +                content = `<${tag.type}>${tag.text}</${tag.type}>`;
```suggestion
                content = `<${tag.type}>
${tag.text}
</${tag.type}>`;
```
i think the newlines make it work better

2023-05-03 00:48 UTC, kafischer commented on core/src/gptTagStream.ts
> +            const completeTag = `<${tag}>${content}</${tag}>`;
```suggestion
            const completeTag = `<${tag}>
${content}
</${tag}>`;
```
same here

2023-05-03 00:53 UTC, kafischer commented on core/src/index.ts
> +  public getPersonalityObject() : Personality {
```suggestion
  public gerPersonality() : Personality {
```

2023-05-03 00:54 UTC, kafischer commented on core/src/index.ts
> +  public setPersonalityObject(obj : Personality) {
```suggestion
  public setPersonality(obj : Personality) {
```

2023-05-03 00:55 UTC, kafischer commented on core/examples/example.ts
> +samantha.setPersonalityObject(p);
not sure about this API?

2023-05-03 00:56 UTC, kafischer commented on core/examples/example.ts
> +samantha.setPersonalityObject(p);
Partial<Personality>?

2023-05-03 00:59 UTC, kafischer commented on core/examples/example.ts
> +samantha.setPersonalityObject(p);
also has the weird implication of the contructor being Samantha but then being renamed

2023-05-03 01:03 UTC, kafischer commented on core/examples/example.ts
> +samantha.setPersonalityObject(p);
i think ideally we'd want to refer to mental architectures by names but like maybe it's

```
const from = Samantha
const soul = new Soul(from)
soul.updatePersonality
```

2023-05-03 01:10 UTC, kafischer commented on core/examples/example.ts
> +samantha.setPersonalityObject(p);
And samantha herself is not modifiable

2023-05-03 07:09 UTC, naynaly10 commented on javascript/src/customization.ts
> +        const strValues = this.values.map(val => val === Complete ? this.fillIn : val).join(' ');
great programmers don't miss that ✅

2023-05-04 19:46 UTC, kafischer commented on core/src/personality.ts
> +export class Personality {
let's go simpler and make Personality simply an interface - i don't see why it needs to be a class

2023-05-04 19:47 UTC, kafischer commented on core/src/soul.ts
> +      You are modeling the mind of ${this.personality.name}, ${this.personality.shortPersonality}
these spaces need to go. Has to be left aligned for performance

2023-05-04 19:47 UTC, kafischer commented on core/src/soul.ts
> +      You are modeling the mind of ${this.personality.name}, ${this.personality.shortPersonality}
```suggestion
You are modeling the mind of ${this.personality.name}, ${this.personality.shortPersonality}
```

2023-05-04 19:47 UTC, kafischer commented on core/src/soul.ts
> +      You are modeling the mind of ${this.personality.name}, ${this.personality.shortPersonality}
eg

2023-05-04 19:47 UTC, kafischer commented on core/src/soul.ts
> +        this.gpt.generate(this.tags, systemPrompt, rememberancePrompt);
same everywhere in the prompts

2023-05-04 19:49 UTC, kafischer commented on core/src/personality.ts
> +
all these spaces need to go on the LH side. has to be left justified

2023-05-04 19:51 UTC, kafischer commented on core/src/personality.ts
> +export class Personality {
Since we don't have any behaviors yet we expect of personality, let's just make it an interface

2023-05-04 19:54 UTC, kafischer requested changes
Great! Excited to get this in

2023-05-04 21:08 UTC, kafischer requested changes
Looks great, caught two minor bugs

2023-05-04 21:08 UTC, kafischer commented on core/src/gptStream.ts
> +                </${tag.type}>`;
```suggestion
${tag.text}
</${tag.type}>`;
```

2023-05-04 21:08 UTC, kafischer commented on core/src/gptStream.ts
> +    if (truncatedMessages.length > 0) {
```suggestion
```
i think this line needs to be removed since the output format is now only contained in the `remembrancePrompt`

2023-05-06 01:30 UTC, merged